<?php

define('DB_USERNAME', 'craveuser');
define('DB_PASSWORD', 'craveuser');
define('DB_HOST', 'cravedatabase.c6u2an6h6rez.us-west-2.rds.amazonaws.com');
define('DB_NAME', 'celitax');
define('DB_PORT', 3306);
 
define('USER_CREATED_SUCCESSFULLY', 0);
define('USER_CREATE_FAILED', 1);
define('USER_ALREADY_EXIST', 2);

define('USER_ALREADY_REQUESTED_PAYMENT', 0);
define('USER_DOES_NOT_EXIST', 1);
define('USER_PAYMENT_REQUEST_SUCCESS', 2);

define('USER_DOESNT_EXIST', 0);
define('USER_PASSWORD_WRONG', 1);
define('USER_LOGIN_SUCCESS', 2);

define('UPLOAD_FAILED_TO_COPY_TO_FOLDER', 0);
define('UPLOAD_FAILED_TO_CREATE_FOLDER', 1);
define('UPLOAD_RECEIPT_NO_FILE_TO_UPLOAD', 2);
define('UPLOAD_FOLDER_NOT_WRITABLE', 3);
define('UPLOAD_SUCCESSFULLY', 4);

define('DELETE_PROFILE_IMAGE_FAILED', 0);
define('DELETE_PROFILE_IMAGE_SUCCESSFULLY', 2);

define('MODIFY_SUCCESS', 0);
define('MODIFY_USER_NOT_EXIST', 1);
define('MODIFY_INVALID_DATA_ACTION', 2);
define('MODIFY_FAILED', 3);
define('MODIFY_TRYING_INSERT_ALREADY_EXISTING', 4);

define('UPDATE_ACCOUNT_SUCCESS', 0);
define('UPDATE_ACCOUNT_FAILED', 1);

define('USER_CHANGE_EMAIL_SUCCESS', 0);
define('USER_CHANGE_EMAIL_ALREADY_EXIST', 1);
define('USER_CHANGE_EMAIL_FAILED', 2);

define('USER_CHANGE_PASSWORD_SUCCESS', 0);
define('USER_CHANGE_PASSWORD_OLD_PASSWORD_WRONG', 1);
define('USER_CHANGE_PASSWORD_FAILED', 2);

define('OPERATION_SUCCESS', 'OPERATION_SUCCESS');
define('UNKNOWN_ERROR', 'UNKNOWN_ERROR');

define('ADD_EXPIRATION_DATE_SUCCESS', 0);
define('ADD_EXPIRATION_DATE_FAILED', 1);

define('NO_EXPIRATION_DATE_EXIST', 'NO_EXPIRATION_DATE_EXIST');

define('CHANGE_PASSWORD_SUCCESS', 0);
define('CHANGE_PASSWORDT_FAILURE', 1);

?>